version: '3.6'
services:
  tap-server:
    build:
      context: .
    image: tap
    container_name: tap
    ports:
      - '7575:7575'
    depends_on: [tap-bd]
  tap-bd:
    image: "postgres:latest"
    container_name: univ
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=univ
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  postgres-data: { }